### ISSUE TITLE
Don't expose credit card details in your repo 

### ISSUE THREAD

**Issue by nombersDev** [vladpikaciu/skinport_bot#2]
Hey man, just a heads up. The credit card details you're using here doesn't appear to be dummy details and just on the off chance that this is actually your real details, you should probably delete them and clear the commit history. 

https://github.com/vladpikaciu/skinport_bot/blob/main/main.py#L80

**Comment by nombersDev** [comment]
Oh I see you've already addressed it, fair enough. Still wouldn't do it but whatever :)

**Comment by vladpikaciu** [comment]
Hi, thanks for being so considerate. I removed the card details altogether. Even if it's still present in the commits, it doesn't affect me as it's a gift card.
